services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
      target: backend
    ports:
      - "4000:4000"
    environment:
      - ENV=Docker
    depends_on:
      - mongodb
  build-frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
      target: frontend
  webserver:
    build:
      context: .
      dockerfile: Dockerfile_frontend
      target: webserver
    ports:
      - "3000:80"
    depends_on:
      - build-frontend